# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  default:
    deps:
      - install
  build:
    cmds:
      - nixos-rebuild build |& nom
    aliases:
      - b
  clean:
    cmds:
      - nix-collect-garbage -d
      - sudo nix-collect-garbage -d
    aliases:
      - c
  install:
    cmds:
      - task: build
      - nixos-rebuild switch --use-remote-sudo
    aliases:
      - i
