[note]
filename = "{{slug title}}"
template = "default.md"


[format.markdown]
link-format = "wiki"
hashtags = true
colon-tags = true
multiword-tags = true


[lsp]
[lsp.diagnostics]
dead-link = "error"


[filter]
recent = "--sort created- --created-after 'last two weeks'"


[alias]
ls = "zk list $@"
last = "zk edit --limit 1 --sort modified- $@"
recent = "zk edit --sort created- --created-after 'last two weeks' --interactive"
