{
  lib,
  pkgs,
  utils ? pkgs.neovim-utils.lib,
}: {
  moduleName,
  nodejsEnv,
  packageEnv,
  pythonEnv,
  runtimeEnv,
}:
  pkgs.writeText "init.lua" ''
    -- Generated by Nix

    -- Lua (including plugins)
    vim.cmd "set packpath^=${packageEnv}"
          package.cpath = "${runtimeEnv}/lib/?.so" .. ";" .. "${packageEnv}/lib/lua/5.1/?.so" .. ";" .. package.cpath

    -- NodeJS
    vim.g.node_host_prog = "${nodejsEnv}/bin/neovim-node-host"

    -- Python
    vim.g.python3_host_prog = "${pythonEnv}/bin/python3"

    require("${moduleName}")
  ''
