{
  config,
  inputs,
  lib,
  pkgs,
  ...
}:
with lib; let
  cfg = config.programs.kitty;
in {
  options.programs.kitty = {
    enable = mkEnableOption "Enable kitty";
    package = mkPackageOption pkgs "kitty" {};
  };

  config = mkIf cfg.enable {
    environment.systemPackages = [cfg.package];

    home = {
      configFile = {
        "kitty/kitty.conf".text = concatStringsSep "\n" [
          ''
            # Generated by Nix
            kitty_mod ctrl+alt
            font_family ${builtins.head config.fonts.fontconfig.defaultFonts.monospace}
            font_size ${builtins.toString config.fonts.fontSize}
            include current-theme.conf
            disable_ligatures always
            enable_audio_bell no
            sync_to_monitor no
            auto_reload_config -1
            allow_remote_control yes
            listen_on unix:@kitty
          ''
        ];
      };

      dataFile = let
        mkScript = name: file:
          pkgs.writeShellApplication {
            inherit name;
            runtimeInputs = with pkgs; [coreutils procps];
            text = ''
              ln -sf ${file} "$HOME/.config/kitty/current-theme.conf" && pkill -SIGUSR1 kitty
            '';
          };
      in {
        "dark-mode.d/kitty".source = lib.getExe (mkScript "kitty-dark" "${inputs.doom-one}/extras/kitty-dark.conf");
        "light-mode.d/kitty".source = lib.getExe (mkScript "kitty-light" "${inputs.doom-one}/extras/kitty-light.conf");
      };
    };
  };
}
